### ISSUE TITLE
Line number not being shown on exception

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/basescript#103]
The actual line number where an error happened in NOT being shown currently. This makes debugging hard.
```bash
2020-04-18T19:50:15.238877Z [error    ] exited start function          host=prashanth-MACH-WX9 id=20200418T195015_d2b1748281ad11ea9e78317ee5a2fdd0 name=gen.py type=log
Traceback (most recent call last):
  File "gen.py", line 306, in <module>
    GeneratorScript().start()
  File "/home/prashanth/.local/lib/python2.7/site-packages/basescript/basescript.py", line 82, in start
    raise e
NameError: global name 'self' is not defined
Exception in thread Thread-1 (most likely raised during interpreter shutdown)
```

With the proposed change, this is the error output which shows error location
```bash
python gen.py run isa.yaml outdir  && cat outdir/insts.c  | indent | less
2020-04-18T19:50:22.353144Z [error    ] exited start function          host=prashanth-MACH-WX9 id=20200418T195022_d6eefc8681ad11ea9e78317ee5a2fdd0 name=gen.py type=log
Traceback (most recent call last):
  File "gen.py", line 306, in <module>
    GeneratorScript().start()
  File "/home/prashanth/.local/lib/python2.7/site-packages/basescript/basescript.py", line 74, in start
    self.args.func()
  File "gen.py", line 258, in run
    self.gen(config)
  File "gen.py", line 268, in gen
    _insts = InstructionConf.gen_insts(inst)
  File "gen.py", line 176, in gen_insts
    _reg = Register.clone(reg)
  File "gen.py", line 78, in clone
    pos=self.pos,
NameError: global name 'self' is not defined
```

**Comment by prashanthellina** [comment]
@jaswanth098 I issued a PR for this (in which I bumped up the version number). Please review + merge and release new version.

**Comment by jaswanth098** [comment]
travis org was down this morning, it is back up will merge the code as soon as Travis run is done

**Comment by jaswanth098** [comment]
Merged the code and made a release closing this.
