### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/basescript#28]
I cloned latest state and did

```bash
sudo pip install .
```

and got

```bash
basescript git:(master) sudo pip install . 
Processing /home/prashanth/code/basescript
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 600, in _prepare_file
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
```

**Comment by algrebe** [comment]
@prashanthellina I am not able to recreate this error. Is it still happening ?

**Comment by prashanthellina** [comment]
@algrebe It doesn't happen now. Closing.
