### ISSUE TITLE
Error with latest version when run without subcommand

### ISSUE THREAD

**Issue by Venkat214** [deep-compute/basescript#65]
This happens when I run my script without specifying any subcommands (i.e. python script.py)

```python
Traceback (most recent call last):
  File "make_phrases.py", line 102, in <module>
    PhraseMakerScript().start()
  File "/home/deepcompute/prashanth/venvs/adjbuilder_pypy/site-packages/basescript/basescript.py", line 57, in __init__
    args['func'] = self.args.func.__name__
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by ghost** [comment]
@Venkat214 
* We are getting this error in `python3` version we will resolve this issue in the next release, Thanks for informing us.

**Comment by ghost** [comment]
* This issue is resolved we can close this ticket.
